baseurl = "http://gerald.sornsen.io"
title = "Gerald Sornsen"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Gerald Sornsen"
    description = "Gerald Sornsen's personal website"
    keywords = "blog,developer,personal"
    info = "Budding Pythonista and Linux Aficionado"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/gsornsen/my_site/commits/"

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/gsornsen/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/sornsen/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"

